require 'capistrano/setup'
require 'capistrano/deploy'
# require 'capistrano/rbenv'
# require 'capistrano/bundler'
# require 'capistrano/overrides/dsl'

# require 'capistrano/funbox/access'
# require 'capistrano/funbox/bundler'
# require 'capistrano/funbox/config'
# require 'capistrano/funbox/secrets'
# require 'capistrano/funbox/database'
# require 'capistrano/funbox/deploy'
# require 'capistrano/funbox/folders'
# require 'capistrano/funbox/git'
# require 'capistrano/funbox/nginx'
# require 'capistrano/funbox/release'
# require 'capistrano/funbox/unicorn'
# require 'capistrano/funbox/unicorn_god'
# require 'capistrano/funbox/puma_god'
require 'capistrano/init_exporter/init'
# require 'capistrano/funbox/whenever'
# require 'capistrano/funbox/logrotator'
# require 'capistrano/funbox/slack'